services:
  cache:
    image: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data

  fingr:
    image: fingr:latest
    command: ["--verbose", "--redis_host", "cache"]
    restart: unless-stopped
    ports:
      - '7979:7979'
    depends_on:
      - cache

volumes:
  cache:
    driver: local
